// Root layout for the entire application.
// This sets up global providers (Clerk), fonts, and a simple header.
import { type Metadata } from 'next'
// Clerk components control what renders for signed in/out users.
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
// Load Google fonts using Next.js font API.
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// Metadata used by the App Router to render <head>.
export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

// The layout wraps all pages under src/app/**
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // Provide Clerk (auth) to the whole tree
    <ClerkProvider>
      <html lang="en">
        <head>
          {/* Optional: react-scan script for performance hints */}
          <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Header shows different content based on auth state */}
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              {/* When logged out: show Sign in / Sign up */}
              <SignInButton forceRedirectUrl="/post-auth" />
              <SignUpButton forceRedirectUrl="/post-auth">
                <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              {/* When logged in: show the user menu */}
              <UserButton />
            </SignedIn>
          </header>
          {/* Page content renders here */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
